<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Create New Block' => '创建新块元素',
  'Manage block' => '管理块元素',
  'edit' => '编辑',
  'Logout{appname}' => '@@@@登出{appname}@@@@',
  'hl\'s tech blog' => '@@@@超喜欢@@@@',
  'About' => '关于本站',
  'Approve Comments' => '管理评论',
  'Bolg' => '博客',
  'Comments ({commentcount})' => '评论 ({commentcount})',
  'Contact' => '交流方式',
  'Create New Post' => '写新文章',
  'Hello,{username}' => '你好,{username}',
  'Home' => '主页',
  'Login' => '登入',
  'Logout' => '登出',
  'Manage Posts' => '文章管理',
  'Permalink' => '阅读',
  'Posts Tagged with' => '标签—',
  'Recent Comment' => '近期评论',
  'Tags' => '标签',
  'on' => '关于',
  '{appname}' => '{appname}',
);
